ALTER TABLE snapshots ADD COLUMN total_complexity INTEGER NOT NULL DEFAULT 0;
ALTER TABLE snapshots ADD COLUMN dead_symbol_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE snapshots ADD COLUMN hotspot_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE snapshots ADD COLUMN health_score INTEGER NOT NULL DEFAULT 0;
