//! `sutra release-pack --md`: the standing-state signals a whole-repo release
//! review needs, curated into bounded markdown (refactor targets, dead
//! candidates, import cycles, co-change pairs with no static edge).
//!
//! These signals don't fit a single diff, so they are not MCP tools
//! (docs/tool-surface-audit.md, "Why a release pack and not four MCP tools").
//! Every section is capped and says when it was cut: incomplete is never clean.
//! A section whose query fails renders as unavailable instead of empty.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::Path;

use crate::components;
use crate::db::Db;
use crate::error::Result;
use crate::history;
use crate::tools::review;

const MAX_REFACTOR_TARGETS: usize = 20;
const MAX_DEAD_SYMBOLS: usize = 40;
const MAX_DEAD_PER_FILE: usize = 8;
const MAX_UNREACHABLE_FILES: usize = 20;
const MAX_CYCLES: usize = 10;
const MAX_FILES_PER_CYCLE: usize = 12;
const MAX_COCHANGE_PAIRS: usize = 20;

/// Liveness the dead-symbol query cannot see. Printed with the candidates so a
/// reviewer reads them as candidates, not verdicts.
const DEAD_KNOWN_MISSES: &[&str] = &[
    "framework-registered items (macro attributes, decorators, route/handler tables)",
    "Python `getattr`/`hasattr` and other string-keyed dispatch",
    "Cargo package renames",
    "entry points reached only from outside the workspace (FFI, plugins, scripts)",
    "public API used by other packages (a library's exports)",
    "the non-default branch of a conditional import (Dart `if (dart.library.*)`)",
];

/// Render the release pack for the workspace at `workspace_root`.
pub fn render_markdown(db: &Db, workspace_id: &str, workspace_root: &Path) -> String {
    let mut out = format!("# Code intel: {workspace_id}\n\n");
    let _ = writeln!(
        out,
        "Generated by `sutra release-pack`. Each section is capped and says when it was cut.\n"
    );
    section(
        &mut out,
        "Refactor targets",
        refactor_targets(db, workspace_root),
    );
    section(&mut out, "Dead candidates", dead_candidates(db));
    section(&mut out, "Import cycles", import_cycles(db));
    section(
        &mut out,
        "Co-change pairs with no static edge",
        uncoupled_cochange(db, workspace_root),
    );
    out
}

fn section(out: &mut String, title: &str, body: Result<String>) {
    let _ = writeln!(out, "## {title}\n");
    match body {
        Ok(body) => out.push_str(&body),
        Err(e) => {
            let _ = writeln!(
                out,
                "_Unavailable: {e}. This section is not clean, it is unknown._"
            );
        }
    }
    out.push('\n');
}

/// "_All 3 shown._" or "_Top 20 of 143 shown; cut._"
fn coverage(shown: usize, total: usize, noun: &str) -> String {
    if shown < total {
        format!("_Top {shown} of {total} {noun} shown; cut._\n")
    } else {
        format!("_All {total} {noun} shown._\n")
    }
}

fn cell(s: &str) -> String {
    format!("`{}`", s.replace('|', "\\|").replace('`', "'"))
}

fn refactor_targets(db: &Db, workspace_root: &Path) -> Result<String> {
    if db.entity_change_count()? == 0 {
        return Err(crate::error::SutraError::Internal(
            "symbol change history is not indexed (run a full parse in a git checkout)".into(),
        ));
    }
    let window = history::window_days(workspace_root)?;
    let cutoff = history::history_cutoff(chrono::Utc::now().timestamp(), window);
    let mut rows: Vec<_> = db
        .symbol_churn_since(cutoff)?
        .into_iter()
        .filter(|r| r.cognitive > 0 && !components::is_test_file(&r.file_path))
        .collect();
    rows.sort_by(|a, b| {
        (b.commits * b.cognitive)
            .cmp(&(a.commits * a.cognitive))
            .then_with(|| a.file_path.cmp(&b.file_path))
            .then_with(|| a.start_line.cmp(&b.start_line))
    });

    let mut out = format!(
        "Symbols ranked by churn × cognitive complexity. Churn is the number of commits in the \
         last {window} days that changed the symbol (cosmetic-only edits excluded). Test files \
         are left out.\n\n"
    );
    if rows.is_empty() {
        out.push_str("None: no symbol with cognitive complexity changed in the window.\n");
        return Ok(out);
    }
    out.push_str("| Symbol | Kind | Location | Churn | Cognitive | Score |\n");
    out.push_str("|---|---|---|---:|---:|---:|\n");
    for r in rows.iter().take(MAX_REFACTOR_TARGETS) {
        let _ = writeln!(
            out,
            "| {} | {} | {}:{} | {} | {} | {} |",
            cell(&r.qualified_name),
            r.kind,
            r.file_path,
            r.start_line,
            r.commits,
            r.cognitive,
            r.commits * r.cognitive,
        );
    }
    out.push('\n');
    out.push_str(&coverage(
        rows.len().min(MAX_REFACTOR_TARGETS),
        rows.len(),
        "symbols",
    ));
    Ok(out)
}

struct DeadItem<'a> {
    name: &'a str,
    kind: &'a str,
    line: i64,
    visibility: &'a str,
}

fn dead_candidates(db: &Db) -> Result<String> {
    let symbols = db.find_dead_symbols(true, None)?;
    let files = db.find_unreachable_files(None)?;

    let mut out = String::from(
        "Symbols with no inbound reference, and files nothing imports. These are \
         candidates, not verdicts. The index cannot see:\n\n",
    );
    for miss in DEAD_KNOWN_MISSES {
        let _ = writeln!(out, "- {miss}");
    }
    out.push('\n');

    // Group by file (the query orders by path, line), largest groups first.
    let mut groups: Vec<(&str, Vec<DeadItem<'_>>)> = Vec::new();
    let mut index: HashMap<&str, usize> = HashMap::new();
    for (qn, path, kind, line, visibility) in &symbols {
        let i = *index.entry(path.as_str()).or_insert_with(|| {
            groups.push((path.as_str(), Vec::new()));
            groups.len() - 1
        });
        groups[i].1.push(DeadItem {
            name: qn,
            kind,
            line: *line,
            visibility: visibility.as_deref().unwrap_or("private"),
        });
    }
    groups.sort_by(|a, b| b.1.len().cmp(&a.1.len()).then_with(|| a.0.cmp(b.0)));

    out.push_str("### Symbols\n\n");
    if symbols.is_empty() {
        out.push_str("None.\n");
    } else {
        let mut shown = 0;
        let mut shown_files = 0;
        for (path, items) in &groups {
            if shown == MAX_DEAD_SYMBOLS {
                break;
            }
            shown_files += 1;
            let _ = writeln!(out, "- **{path}**");
            let take = items
                .len()
                .min(MAX_DEAD_PER_FILE)
                .min(MAX_DEAD_SYMBOLS - shown);
            for item in &items[..take] {
                let _ = writeln!(
                    out,
                    "  - {} ({} {}, line {})",
                    cell(item.name),
                    item.visibility,
                    item.kind,
                    item.line
                );
            }
            shown += take;
            if take < items.len() {
                let _ = writeln!(
                    out,
                    "  - _{} more in this file not listed._",
                    items.len() - take
                );
            }
        }
        out.push('\n');
        let _ = writeln!(
            out,
            "_{shown} of {} candidates shown (at most {MAX_DEAD_PER_FILE} per file){}._",
            symbols.len(),
            if shown < symbols.len() { "; cut" } else { "" }
        );
        if shown_files < groups.len() {
            let _ = writeln!(
                out,
                "_{} more files with candidates not listed._",
                groups.len() - shown_files
            );
        }
    }

    out.push_str("\n### Unreachable files\n\n");
    if files.is_empty() {
        out.push_str("None.\n");
    } else {
        for (path, lines) in files.iter().take(MAX_UNREACHABLE_FILES) {
            let _ = writeln!(out, "- {path} ({lines} lines)");
        }
        out.push('\n');
        out.push_str(&coverage(
            files.len().min(MAX_UNREACHABLE_FILES),
            files.len(),
            "files",
        ));
    }
    Ok(out)
}

fn import_cycles(db: &Db) -> Result<String> {
    let paths: HashMap<i64, std::sync::Arc<str>> = db
        .all_files()?
        .into_iter()
        .map(|f| (f.id, f.path))
        .collect();
    let mut sccs: Vec<Vec<&str>> = crate::graph::find_import_sccs(&db.import_edges()?)
        .into_iter()
        .map(|scc| {
            let mut files: Vec<&str> = scc
                .iter()
                .filter_map(|id| paths.get(id).map(|p| &**p))
                .collect();
            files.sort_unstable();
            files
        })
        .collect();
    sccs.sort_by(|a, b| b.len().cmp(&a.len()).then_with(|| a.cmp(b)));

    let mut out =
        String::from("Groups of files that import each other (strongly connected components).\n\n");
    if sccs.is_empty() {
        out.push_str("None.\n");
        return Ok(out);
    }
    for (n, files) in sccs.iter().take(MAX_CYCLES).enumerate() {
        let _ = writeln!(out, "{}. {} files", n + 1, files.len());
        for f in files.iter().take(MAX_FILES_PER_CYCLE) {
            let _ = writeln!(out, "   - {f}");
        }
        if files.len() > MAX_FILES_PER_CYCLE {
            let _ = writeln!(
                out,
                "   - _{} more files in this cycle not listed._",
                files.len() - MAX_FILES_PER_CYCLE
            );
        }
    }
    out.push('\n');
    out.push_str(&coverage(sccs.len().min(MAX_CYCLES), sccs.len(), "cycles"));
    Ok(out)
}

fn uncoupled_cochange(db: &Db, workspace_root: &Path) -> Result<String> {
    let threshold = review::cochange_threshold(workspace_root)?;
    let pairs = review::uncoupled_cochange_pairs(db, threshold)?;

    let mut out = format!(
        "File pairs that change together (jaccard ≥ {threshold}) with no import or reference \
         between them: coupling the code does not state.\n\n"
    );
    if pairs.is_empty() {
        out.push_str("None.\n");
        return Ok(out);
    }
    out.push_str("| File | Partner | Jaccard | Shared commits |\n");
    out.push_str("|---|---|---:|---:|\n");
    for p in pairs.iter().take(MAX_COCHANGE_PAIRS) {
        let _ = writeln!(
            out,
            "| {} | {} | {:.2} | {} |",
            p.a_path, p.b_path, p.jaccard, p.shared_commits
        );
    }
    out.push('\n');
    out.push_str(&coverage(
        pairs.len().min(MAX_COCHANGE_PAIRS),
        pairs.len(),
        "pairs",
    ));
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn coverage_marks_a_cut() {
        assert_eq!(
            coverage(20, 143, "symbols"),
            "_Top 20 of 143 symbols shown; cut._\n"
        );
        assert_eq!(coverage(3, 3, "files"), "_All 3 files shown._\n");
    }

    #[test]
    fn empty_index_renders_every_section_and_flags_missing_history() {
        let dir = tempfile::tempdir().expect("tempdir");
        let db = Db::open_unchecked("release_pack", dir.path()).expect("open db");
        let md = render_markdown(&db, "release_pack", dir.path());
        for title in [
            "## Refactor targets",
            "## Dead candidates",
            "## Import cycles",
            "## Co-change pairs with no static edge",
        ] {
            assert!(md.contains(title), "missing {title}:\n{md}");
        }
        // No symbol history is unknown, not "no refactor targets".
        assert!(
            md.contains("_Unavailable: ") && md.contains("symbol change history is not indexed"),
            "{md}"
        );
    }
}
